FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4

USER root:0
RUN microdnf install wget curl tar gzip shadow-utils \
 && mkdir -p /opt/steampipe \
 && chmod -R g+rwX /opt \
 && useradd --uid 9998 --gid 0 steampipe --base-dir /opt

# steampipe install works if I use their install script
# manually installing the binary has been failing for me
ENV STEAMPIPE_VERSION=0.5.1
RUN echo \\
 && cd /tmp \
 && wget -nv https://raw.githubusercontent.com/turbot/steampipe/${STEAMPIPE_VERSION}/install.sh \
 && chmod a+rx ./install.sh \
 && ./install.sh ${STEAMPIPE_VERSION} \
 && rm install.sh \
 && echo

# plugin installs and initialization need to be as non-root
# I haven't gotten an anonymous uid to work here yet, so far I am
# setting 'anyuid' for the steampipe service-acct
USER steampipe:0
WORKDIR /opt/steampipe
# note there seems to be an initial error message but it is working
RUN steampipe plugin install steampipe kubernetes

# with write-pod-kubeconfig don't think I need this, but I'll leave it for now
# in case it is useful for debugging
#ENV OC_CLIENT_RELEASE=4.6.0-0.okd-2021-01-23-132511
#RUN echo \
# && cd /tmp \
# && wget -nv https://github.com/openshift/okd/releases/download/${OC_CLIENT_RELEASE}/openshift-client-linux-${OC_CLIENT_RELEASE}.tar.gz \
# && tar xzf openshift-client-linux-${OC_CLIENT_RELEASE}.tar.gz \
# && mv kubectl /opt/steampipe \
# && rm -rf /tmp/openshift-client-linux-${OC_CLIENT_RELEASE}.tar.gz \
# && echo

COPY ./write-pod-kubeconfig /opt/steampipe/write-pod-kubeconfig
COPY ./kubernetes.spc /opt/steampipe/.steampipe/config/kubernetes.spc

# This should run correctly during your container build
RUN steampipe query "select name from steampipe_registry_plugin"

CMD /opt/steampipe service start --database-listen network --database-port 9193
