#!/bin/bash

cat > $1 <<EOF
apiVersion: v1
kind: Config
preferences: {}
clusters:
  - name: pod-cluster
    cluster:
      insecure-skip-tls-verify: true
      server: 'https://kubernetes.default:443'
users:
  - name: pod-user
    user:
      token: $(cat /run/secrets/kubernetes.io/serviceaccount/token)
contexts:
  - name: pod-context
    context:
      cluster: pod-cluster
      namespace: $(cat /run/secrets/kubernetes.io/serviceaccount/namespace)
      user: pod-user
current-context: pod-context
EOF
